/**
 * Fetches 5etools spell JSONs, merges them, applies PT-BR names, outputs spell-catalog.json
 * Run: bun scripts/build-spells.mjs
 */

import { writeFileSync, mkdirSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, '../src/data/spell-catalog.json')

const SOURCES = [
  'https://raw.githubusercontent.com/ariestae/5etools/master/data/spells/spells-phb.json',
  'https://raw.githubusercontent.com/ariestae/5etools/master/data/spells/spells-xge.json',
  'https://raw.githubusercontent.com/ariestae/5etools/master/data/spells/spells-scag.json',
]

const SCHOOL_PT = {
  A: 'Abjuração',
  C: 'Conjuração',
  D: 'Adivinhação',
  E: 'Encantamento',
  V: 'Evocação',
  I: 'Ilusão',
  N: 'Necromancia',
  T: 'Transmutação',
}

const CLASS_MAP = {
  wizard: 'Wizard',
  bard: 'Bard',
  ranger: 'Ranger',
}

// PT names from official BR PHB + community sources (key = lowercase english name)
const NAME_PT = {
  'acid splash': 'Respingo Ácido',
  'aid': 'Auxílio',
  'alarm': 'Alarme',
  'alter self': 'Alterar Aparência',
  'animal friendship': 'Amizade Animal',
  'animal messenger': 'Mensageiro Animal',
  'animate dead': 'Animar Mortos',
  'animate objects': 'Animar Objetos',
  'antilife shell': 'Barreira Antivida',
  'antimagic field': 'Campo Antimagia',
  'arcane eye': 'Olho Arcano',
  'arcane lock': 'Tranca Arcana',
  'armor of agathys': 'Armadura de Agathys',
  'arms of hadar': 'Braços de Hadar',
  'astral projection': 'Projeção Astral',
  'augury': 'Augúrio',
  'aura of life': 'Aura de Vida',
  'aura of purity': 'Aura de Pureza',
  'aura of vitality': 'Aura de Vitalidade',
  'awaken': 'Despertar',
  'bane': 'Aflição',
  'banishment': 'Banimento',
  'barkskin': 'Pele de Árvore',
  'beacon of hope': 'Sinal de Esperança',
  'beast sense': 'Sentidos da Besta',
  'bestow curse': 'Impor Maldição',
  'blade barrier': 'Barreira de Lâminas',
  'blade ward': 'Proteção contra Lâminas',
  'bless': 'Bênção',
  'blight': 'Ferrugem',
  'blindness/deafness': 'Cegueira/Surdez',
  'blink': 'Piscar',
  'blur': 'Borrão',
  'branding smite': 'Punição Marcante',
  'burning hands': 'Mãos Flamejantes',
  'call lightning': 'Invocar Raios',
  'calm emotions': 'Acalmar Emoções',
  'catapult': 'Catapulta',
  'catnap': 'Cochilo',
  'cause fear': 'Causar Medo',
  'chain lightning': 'Corrente de Relâmpagos',
  'charm person': 'Enfeitiçar Pessoa',
  'chill touch': 'Toque Gélido',
  'chromatic orb': 'Orbe Cromático',
  'circle of death': 'Círculo da Morte',
  'circle of power': 'Círculo de Poder',
  'clairvoyance': 'Clarividência',
  'clone': 'Clone',
  'cloud of daggers': 'Nuvem de Adagas',
  'cloudkill': 'Morte Nebulosa',
  'color spray': 'Leque Cromático',
  'command': 'Comando',
  'commune': 'Comunhão',
  'commune with nature': 'Comunhão com a Natureza',
  'compelled duel': 'Duelo Compelido',
  'comprehend languages': 'Compreender Idiomas',
  'compulsion': 'Compulsão',
  'cone of cold': 'Cone de Frio',
  'confusion': 'Confusão',
  'conjure animals': 'Conjurar Animais',
  'conjure barrage': 'Conjurar Barragem',
  'conjure celestial': 'Conjurar Celestial',
  'conjure elemental': 'Conjurar Elemental',
  'conjure fey': 'Conjurar Fada',
  'conjure minor elementals': 'Conjurar Elementais Menores',
  'conjure volley': 'Conjurar Salva',
  'conjure woodland beings': 'Conjurar Criaturas da Floresta',
  'contact other plane': 'Contato Extraplanar',
  'contagion': 'Contágio',
  'contingency': 'Contingência',
  'continual flame': 'Chama Contínua',
  'control flames': 'Controlar Chamas',
  'control water': 'Controlar Água',
  'control weather': 'Controlar o Clima',
  'counterspell': 'Contramágica',
  'create bonfire': 'Criar Fogueira',
  'create food and water': 'Criar Comida e Água',
  'create or destroy water': 'Criar ou Destruir Água',
  'create undead': 'Criar Mortos-Vivos',
  'creation': 'Criação',
  'crown of madness': 'Coroa da Loucura',
  'crown of stars': 'Coroa de Estrelas',
  'crusader\'s mantle': 'Manto do Cruzado',
  'cure wounds': 'Curar Ferimentos',
  'dancing lights': 'Luzes Dançantes',
  'darkness': 'Escuridão',
  'darkvision': 'Visão no Escuro',
  'daylight': 'Luz do Dia',
  'death ward': 'Proteção contra a Morte',
  'delayed blast fireball': 'Bola de Fogo Retardada',
  'demiplane': 'Semiplano',
  'destructive wave': 'Onda Destrutiva',
  'detect evil and good': 'Detectar o Bem e o Mal',
  'detect magic': 'Detectar Magia',
  'detect poison and disease': 'Detectar Veneno e Doença',
  'detect thoughts': 'Detectar Pensamentos',
  'dimension door': 'Porta Dimensional',
  'disguise self': 'Disfarçar-se',
  'disintegrate': 'Desintegrar',
  'dispel evil and good': 'Dissipar o Bem e o Mal',
  'dispel magic': 'Dissipar Magia',
  'dissonant whispers': 'Sussurros Dissonnantes',
  'distort value': 'Distorcer Valor',
  'divination': 'Adivinhação',
  'divine favor': 'Favor Divino',
  'divine word': 'Palavra Divina',
  'dominate beast': 'Dominar Besta',
  'dominate monster': 'Dominar Monstro',
  'dominate person': 'Dominar Pessoa',
  'dragon\'s breath': 'Sopro do Dragão',
  'drawmij\'s instant summons': 'Evocação Instantânea de Drawmij',
  'dream': 'Sonho',
  'druidcraft': 'Truque Druídico',
  'dust devil': 'Redemoinho de Pó',
  'earth tremor': 'Tremor de Terra',
  'earthbind': 'Aprisionamento Terrestre',
  'earthquake': 'Terremoto',
  'eldritch blast': 'Raio Eldritch',
  'elemental bane': 'Ruína Elemental',
  'elemental weapon': 'Arma Elemental',
  'enhance ability': 'Aprimorar Habilidade',
  'enlarge/reduce': 'Aumentar/Reduzir',
  'ensnaring strike': 'Ataque Enredador',
  'entangle': 'Enredar',
  'enthrall': 'Cativar',
  'erupting earth': 'Terra Erguendo-se',
  'etherealness': 'Forma Etérea',
  'evard\'s black tentacles': 'Tentáculos Negros de Evard',
  'expeditious retreat': 'Retirada Acelerada',
  'eyebite': 'Mordida',
  'fabricate': 'Fabricar',
  'faerie fire': 'Fogo das Fadas',
  'false life': 'Vida Falsa',
  'fear': 'Medo',
  'feather fall': 'Queda Suave',
  'feeblemind': 'Defeituoso Mental',
  'feign death': 'Fingir de Morto',
  'find familiar': 'Encontrar Familiar',
  'find steed': 'Encontrar Montaria',
  'find the path': 'Encontrar o Caminho',
  'find traps': 'Encontrar Armadilhas',
  'finger of death': 'Dedo da Morte',
  'fire bolt': 'Raio de Fogo',
  'fire shield': 'Escudo de Fogo',
  'fire storm': 'Tempestade de Fogo',
  'fireball': 'Bola de Fogo',
  'flame blade': 'Lâmina Flamejante',
  'flame strike': 'Coluna de Chamas',
  'flaming sphere': 'Esfera Flamejante',
  'flesh to stone': 'Carne em Pedra',
  'fly': 'Voar',
  'fog cloud': 'Nuvem de Névoa',
  'forbiddance': 'Proibição',
  'forcecage': 'Jaula de Força',
  'foresight': 'Previsão',
  'freedom of movement': 'Liberdade de Movimentos',
  'friends': 'Amigos',
  'gaseous form': 'Forma Gasosa',
  'gate': 'Portal',
  'geas': 'Geas',
  'gentle repose': 'Repouso Gentil',
  'giant insect': 'Inseto Gigante',
  'glibness': 'Lábia',
  'globe of invulnerability': 'Globo de Invulnerabilidade',
  'glyph of warding': 'Glifo de Proteção',
  'goodberry': 'Frutos Mágicos',
  'grasping vine': 'Videira Estranguladora',
  'grasping weeds': 'Ervas Enredadoras',
  'grease': 'Graxa',
  'greater invisibility': 'Invisibilidade Maior',
  'greater restoration': 'Restauração Maior',
  'guardian of faith': 'Guardião da Fé',
  'guardian of nature': 'Guardião da Natureza',
  'guards and wards': 'Guardas e Sentinela',
  'guidance': 'Orientação',
  'guiding bolt': 'Raio Guiador',
  'gust': 'Rajada',
  'gust of wind': 'Lufada de Vento',
  'hail of thorns': 'Chuva de Espinhos',
  'hallow': 'Santificar',
  'hallucinatory terrain': 'Terreno Alucinógeno',
  'harm': 'Prejudicar',
  'haste': 'Acelerar',
  'heal': 'Curar',
  'healing spirit': 'Espírito Curador',
  'healing word': 'Palavra de Cura',
  'heat metal': 'Aquecer Metal',
  'hellish rebuke': 'Revide Infernal',
  'heroes\' feast': 'Banquete dos Heróis',
  'heroism': 'Heroísmo',
  'hex': 'Maldição',
  'hold monster': 'Imobilizar Monstro',
  'hold person': 'Imobilizar Pessoa',
  'holy aura': 'Aura Sagrada',
  'hunger of hadar': 'Fome de Hadar',
  'hunter\'s mark': 'Marca do Caçador',
  'hypnotic pattern': 'Padrão Hipnótico',
  'ice knife': 'Faca de Gelo',
  'ice storm': 'Tempestade de Gelo',
  'identify': 'Identificar',
  'illusory script': 'Texto Ilusório',
  'imprisonment': 'Aprisionamento',
  'incendiary cloud': 'Nuvem Incendiária',
  'inflict wounds': 'Infligir Ferimentos',
  'insect plague': 'Praga de Insetos',
  'invisibility': 'Invisibilidade',
  'jump': 'Salto',
  'knock': 'Abrir',
  'legend lore': 'Lendas',
  'leomund\'s secret chest': 'Baú Secreto de Leomund',
  'leomund\'s tiny hut': 'Cabana Minúscula de Leomund',
  'lesser restoration': 'Restauração Menor',
  'levitate': 'Levitar',
  'light': 'Luz',
  'lightning arrow': 'Flecha Relâmpago',
  'lightning bolt': 'Relâmpago',
  'lightning lure': 'Atração Elétrica',
  'locate animals or plants': 'Localizar Animais ou Plantas',
  'locate creature': 'Localizar Criatura',
  'locate object': 'Localizar Objeto',
  'longstrider': 'Passos Longos',
  'mage armor': 'Armadura Arcana',
  'mage hand': 'Mão Mágica',
  'magic circle': 'Círculo Mágico',
  'magic jar': 'Jarro Mágico',
  'magic missile': 'Mísseis Mágicos',
  'magic mouth': 'Boca Mágica',
  'magic weapon': 'Arma Mágica',
  'major image': 'Imagem Maior',
  'mass cure wounds': 'Curar Ferimentos em Massa',
  'mass heal': 'Curar em Massa',
  'mass healing word': 'Palavra de Cura em Massa',
  'mass suggestion': 'Sugestão em Massa',
  'maze': 'Labirinto',
  'meld into stone': 'Fundir-se à Pedra',
  'melf\'s minute meteors': 'Meteoros Minúsculos de Melf',
  'mending': 'Remendo',
  'message': 'Mensagem',
  'meteor swarm': 'Enxame de Meteoros',
  'mind blank': 'Mente em Branco',
  'mind sliver': 'Estilhaço Mental',
  'minor illusion': 'Ilusão Menor',
  'mirage arcane': 'Miragem Arcana',
  'mirror image': 'Reflexão',
  'mislead': 'Enganar',
  'misty step': 'Passo Nebuloso',
  'modify memory': 'Modificar Memória',
  'moonbeam': 'Raio de Lua',
  'mordenkainen\'s faithful hound': 'Cão Fiel de Mordenkainen',
  'mordenkainen\'s magnificent mansion': 'Mansão Magnífica de Mordenkainen',
  'mordenkainen\'s private sanctum': 'Santuário Privado de Mordenkainen',
  'mordenkainen\'s sword': 'Espada de Mordenkainen',
  'move earth': 'Mover Terra',
  'nondetection': 'Antidetecção',
  'nystul\'s magic aura': 'Aura Mágica de Nystul',
  'otiluke\'s freezing sphere': 'Esfera Glacial de Otiluke',
  'otiluke\'s resilient sphere': 'Esfera Resiliente de Otiluke',
  'ott\'s irresistible dance': 'Dança Irresistível de Otto',
  'pass without trace': 'Passos sem Pegadas',
  'passwall': 'Abrir Passagem',
  'phantasmal force': 'Força Fantasmagórica',
  'phantasmal killer': 'Assassino Fantasmagórico',
  'phantom steed': 'Corcel Fantasmagórico',
  'planar ally': 'Aliado Planar',
  'planar binding': 'Vínculo Planar',
  'plane shift': 'Mudança de Plano',
  'plant growth': 'Crescimento de Plantas',
  'poison spray': 'Rajada Venenosa',
  'polymorph': 'Metamorfose',
  'power word heal': 'Palavra de Poder: Curar',
  'power word kill': 'Palavra de Poder: Matar',
  'power word pain': 'Palavra de Poder: Dor',
  'power word stun': 'Palavra de Poder: Atordoar',
  'prayer of healing': 'Oração de Cura',
  'prestidigitation': 'Prestidigitação',
  'primal savagery': 'Selvageria Primal',
  'primordial ward': 'Proteção Primordial',
  'private sanctum': 'Santuário Privado',
  'produce flame': 'Chamas Produzidas',
  'programmed illusion': 'Ilusão Programada',
  'project image': 'Projetar Imagem',
  'protection from energy': 'Proteção contra Energia',
  'protection from evil and good': 'Proteção contra o Bem e o Mal',
  'protection from poison': 'Proteção contra Veneno',
  'purify food and drink': 'Purificar Comida e Bebida',
  'raise dead': 'Reviver os Mortos',
  'rary\'s telepathic bond': 'Vínculo Telepático de Rary',
  'ray of enfeeblement': 'Raio de Enfraquecimento',
  'ray of frost': 'Raio de Gelo',
  'ray of sickness': 'Raio de Enjoo',
  'regenerate': 'Regenerar',
  'reincarnate': 'Reencarnar',
  'remove curse': 'Remover Maldição',
  'resistance': 'Resistência',
  'resurrection': 'Ressurreição',
  'reverse gravity': 'Inverter a Gravidade',
  'revivify': 'Reviver',
  'rope trick': 'Truque da Corda',
  'sacred flame': 'Chama Sagrada',
  'sanctuary': 'Santuário',
  'scorching ray': 'Raio Ardente',
  'scrying': 'Vidência',
  'searing smite': 'Punição Ardente',
  'see invisibility': 'Ver o Invisível',
  'seeming': 'Aparência',
  'sending': 'Enviar Mensagem',
  'sequester': 'Sepultar',
  'shape water': 'Moldar Água',
  'shapechange': 'Metamorfose Superior',
  'shatter': 'Estilhaçar',
  'shield': 'Escudo',
  'shield of faith': 'Escudo da Fé',
  'shillelagh': 'Bordão Místico',
  'shocking grasp': 'Toque Chocante',
  'silence': 'Silêncio',
  'silent image': 'Imagem Silenciosa',
  'simulacrum': 'Simulacro',
  'sleep': 'Sono',
  'sleet storm': 'Tempestade de Granizo',
  'slow': 'Lentidão',
  'snare': 'Laço',
  'soul cage': 'Gaiola da Alma',
  'spare the dying': 'Poupar os Moribundos',
  'speak with animals': 'Falar com Animais',
  'speak with dead': 'Falar com os Mortos',
  'speak with plants': 'Falar com Plantas',
  'spider climb': 'Escalar como Aranha',
  'spike growth': 'Crescimento de Espinhos',
  'spirit guardians': 'Guardiões Espirituais',
  'spiritual weapon': 'Arma Espiritual',
  'staggering smite': 'Punição Estonteante',
  'stinking cloud': 'Nuvem Fétida',
  'stone shape': 'Moldar Pedra',
  'stoneskin': 'Pele de Pedra',
  'storm of vengeance': 'Tempestade da Vingança',
  'suggestion': 'Sugestão',
  'sunbeam': 'Raio de Sol',
  'sunburst': 'Explosão Solar',
  'swift quiver': 'Aljava Veloz',
  'symbol': 'Símbolo',
  'tasha\'s caustic brew': 'Poção Cáustica de Tasha',
  'tasha\'s hideous laughter': 'Risada Horrível de Tasha',
  'tasha\'s mind whip': 'Chicote Mental de Tasha',
  'tasha\'s otherworldly guise': 'Disfarce Sobrenatural de Tasha',
  'telekinesis': 'Telecinese',
  'telepathy': 'Telepatia',
  'teleport': 'Teletransporte',
  'teleportation circle': 'Círculo de Teletransporte',
  'tenser\'s floating disk': 'Disco Flutuante de Tenser',
  'tenser\'s transformation': 'Transformação de Tenser',
  'thaumaturgy': 'Taumaturgia',
  'thorn whip': 'Chicote de Espinhos',
  'thunder step': 'Passo Trovejante',
  'thunderclap': 'Estrondo',
  'thunderous smite': 'Punição Trovejante',
  'thunderwave': 'Onda Trovejante',
  'tidal wave': 'Onda Gigante',
  'time stop': 'Parar o Tempo',
  'tiny servant': 'Servo Minúsculo',
  'tongues': 'Línguas',
  'transport via plants': 'Transporte por Plantas',
  'tree stride': 'Passo Arbóreo',
  'true polymorph': 'Metamorfose Verdadeira',
  'true resurrection': 'Ressurreição Verdadeira',
  'true seeing': 'Visão Verdadeira',
  'true strike': 'Golpe Certeiro',
  'tsunami': 'Tsunami',
  'unseen servant': 'Servo Invisível',
  'vampiric touch': 'Toque Vampírico',
  'vicious mockery': 'Zombaria Viciosa',
  'vitriolic sphere': 'Esfera Vítrea',
  'wall of fire': 'Muralha de Fogo',
  'wall of force': 'Muralha de Força',
  'wall of ice': 'Muralha de Gelo',
  'wall of light': 'Muralha de Luz',
  'wall of sand': 'Muralha de Areia',
  'wall of stone': 'Muralha de Pedra',
  'wall of thorns': 'Muralha de Espinhos',
  'wall of water': 'Muralha de Água',
  'warding bond': 'Vínculo Protetor',
  'warding wind': 'Vento Protetor',
  'water breathing': 'Respirar na Água',
  'water walk': 'Caminhar na Água',
  'watery sphere': 'Esfera Aquosa',
  'web': 'Teia',
  'weird': 'Pavor',
  'wind walk': 'Caminhar no Vento',
  'wind wall': 'Muralha de Vento',
  'wish': 'Desejo',
  'witch bolt': 'Raio da Bruxa',
  'word of radiance': 'Palavra da Radiação',
  'word of recall': 'Palavra de Regresso',
  'wrathful smite': 'Punição Irada',
  'zephyr strike': 'Ataque do Zéfiro',
  'zone of truth': 'Zona da Verdade',
  'absorb elements': 'Absorver Elementos',
  'booming blade': 'Lâmina Trovejante',
  'green-flame blade': 'Lâmina de Chamas Verdes',
  'lightning lure': 'Atração Elétrica',
  'sword burst': 'Explosão de Espadas',
  'snilloc\'s snowball swarm': 'Enxame de Bolas de Neve de Snilloc',
  'aganazzar\'s scorcher': 'Chama de Aganazzar',
  'maximilian\'s earthen grasp': 'Aperto de Maximilian',
  'skywrite': 'Escrever no Céu',
  'crown of stars': 'Coroa de Estrelas',
  'danse macabre': 'Dança Macabra',
  'control winds': 'Controlar Ventos',
  'immolation': 'Imolação',
  'investiture of flame': 'Investidura de Chamas',
  'investiture of ice': 'Investidura de Gelo',
  'investiture of stone': 'Investidura de Pedra',
  'investiture of wind': 'Investidura de Vento',
  'mental prison': 'Prisão Mental',
  'mighty fortress': 'Fortaleza Poderosa',
  'power word pain': 'Palavra de Poder: Dor',
  'scatter': 'Dispersar',
  'shadow of moil': 'Sombra de Moil',
  'sickening radiance': 'Radiação Enjoativa',
  'skill empowerment': 'Fortalecimento de Habilidade',
  'synaptic static': 'Estática Sináptica',
  'temple of the gods': 'Templo dos Deuses',
  'whirlwind': 'Redemoinho',
  'wrath of nature': 'Ira da Natureza',
}

function normalizeKey(name) {
  return name.toLowerCase().trim()
}

function translateName(enName) {
  return NAME_PT[normalizeKey(enName)] ?? enName
}

function getClasses(spell) {
  const classes = new Set()
  const list = spell.classes?.fromClassList ?? []
  for (const entry of list) {
    if (entry.name) classes.add(entry.name)
  }
  return [...classes]
}

function spellKey(spell) {
  return `${spell.name}|${spell.source ?? 'UNK'}`
}

async function fetchJson(url) {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`Failed ${url}: ${res.status}`)
  return res.json()
}

async function main() {
  const byKey = new Map()

  for (const url of SOURCES) {
    const data = await fetchJson(url)
    for (const spell of data.spell ?? []) {
      if (!spell.name || spell.level === undefined) continue
      const key = spellKey(spell)
      if (!byKey.has(key)) {
        byKey.set(key, {
          id: key,
          nameEn: spell.name,
          name: translateName(spell.name),
          level: spell.level,
          school: SCHOOL_PT[spell.school] ?? spell.school,
          schoolCode: spell.school,
          classes: getClasses(spell),
          source: spell.source,
          ritual: Boolean(spell.meta?.ritual || spell.ritual),
        })
      }
    }
  }

  const catalog = [...byKey.values()].sort((a, b) => {
    if (a.level !== b.level) return a.level - b.level
    return a.name.localeCompare(b.name, 'pt-BR')
  })

  mkdirSync(dirname(OUT), { recursive: true })
  const payload = JSON.stringify(catalog)
  if (payload.includes('\uFFFD') || /Ã.|Â./.test(payload)) {
    throw new Error('Generated spell catalog contains replacement or mojibake characters')
  }
  writeFileSync(OUT, payload, 'utf8')
  console.log(`Wrote ${catalog.length} spells to ${OUT}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
